version: '3.6'

services:
  netbox_react_agent:
    image: byrn-baker/nautobot_react_agent:nautobot_react_agent
    container_name: nautobot_react_agent
    restart: always
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile   
    ports:
      - "8501:8501"