version: '3.6'

networks:
  ollama:

services:
  ollama:
    image: ollama/ollama
    build: 
      context: ./
      dockerfile: ./ollama/Dockerfile     
    networks:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - ./data/ollama:/root/.ollama
    ports:
      - 11434:11434

  nautobot_react_agent:
    build: 
      context: ./
      dockerfile: ./docker/Dockerfile   
    container_name: nautobot_react_agent
    restart: always
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    networks:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434      
